// Bilingual content for Lux & Co. Consulting site
// PT (default) / EN

window.LUX_CONTENT = {
  pt: {
    nav: {
      sobre: "Mentor",
      consultoria: "Consultoria",
      mentoria: "Mentoria",
      modulos: "Módulos",
      caderno: "Caderno · Grátis",
      contato: "Contato",
      empresa: "Para Empresas",
    },
    hero: {
      eyebrow: "",
      title: "Chega de girar em volta do que você poderia ser.\nÉ hora de ser.",
      sub: "",
      ctaConsultoria: "Sobre a Consultoria",
      ctaMentor: "Sobre o Mentor",
      ctaContato: "Entre em contato",
    },
    about: {
      eyebrow: "Sobre o mentor",
      title: "Seu problema não é falta de ESFORÇO. É falta de ESTRATÉGIA.",
      identity: {
        name: "Michel Camara Berestinas",
        meta: [
          ["Idade", "38 anos"],
          ["Natural de", "São Paulo, Brasil"],
          ["Baseado em", "Sydney, Austrália"],
          ["Atendimento", "Worldwide · online"],
        ],
        role: "Project Manager & Account Manager (Google Reviews) · Fundador da Lux & Co. Consulting",
      },
      bodyParas: [
        "Olá, meu nome é Michel C. Berestinas. Tenho 38 anos, sou natural de São Paulo e hoje vivo em Sydney, Australia, atendendo pessoas worldwide. Com mais de 15 anos de experiência profissional, construí minha trajetória em empresas como EY, Carrefour e American Express, em Project Management e Account Management na área de Google Reviews, atuando em ambientes desafiadores, dinâmicos e orientados a resultados.",
        "Ao longo dessa caminhada, desenvolvi uma visão prática sobre estratégia, negócios, pessoas, processos, atendimento, liderança e tomada de decisão. Aprendi, na prática, que o crescimento não acontece apenas por esforço, mas também por clareza, direção, consistência e capacidade de tomar boas decisões no momento certo.",
        "Minha experiência me ensinou a olhar para problemas com visão estratégica, a entender cenários complexos, a organizar prioridades e a transformar ideias em ações viáveis. Mas minha história não foi construída apenas por conquistas, também vivi fases de pressão, incerteza, recomeços e reconstrução.",
        "Esses desafios fortaleceram minha forma de enxergar a vida, o trabalho e o desenvolvimento pessoal. Com o tempo, entendi que muitas pessoas não estão paradas por falta de potencial, mas por falta de clareza, estrutura, direção e apoio para organizar o que vivem.",
        "Hoje, transformo essa bagagem em uma mentoria prática, humana e estratégica, ajudando pessoas a entenderem onde estão, reconhecerem seus padrões, tomarem decisões mais conscientes e construírem um caminho mais alinhado com seus valores, forças e propósito.",
      ],
      methodEyebrow: "",
      stats: [
        ["15+", "anos de experiência"],
        ["3", "corporações globais"],
        ["1:1", "atendimento personalizado"],
        ["FSF", "Criado do método FSF"],
      ],
      brands: ["EY", "Carrefour", "American Express", "Google Reviews"],
      pullquote: "Ninguém acorda um dia e descobre que a vida mudou sozinha. Você pode continuar esperando pelo momento certo, ou decidir que o momento é agora e construir a partir do que você já tem.",
      signature: ", Fundador, Lux & Co.",
    },
    consultancy: {
      eyebrow: "Sobre a consultoria",
      welcome: "Bem-vindo.",
      bodyParas: [
        "Muitas pessoas carregam dons, ideias e sonhos, mas sem clareza e estrutura ou direção, esses potenciais ficam parados.",
        "Esta mentoria existe para mudar isso.",
        "Aqui, você vai entender quem você é, identificar o que está travando o seu avanço e construir um caminho prático para sua vida, carreira e negócios.",
        "Não trabalhamos com fórmulas genéricas. Trabalhamos com o que já existe dentro de você, organizando e fortalecendo e colocando em movimento.",
        "Seja para liderar com mais clareza, empreender com mais critério ou simplesmente viver com mais propósito: este é o espaço certo.",
      ],
      quote: "Ambientes transformados começam quando alguém decide pensar diferente.",
      quoteAuthor: "Bill Johnson, líder da Bethel Church",
    },
    mentorship: {
      eyebrow: "Minha mentoria",
      title: "Uma jornada estruturada em 6 módulos.",
      lead: "Não é fórmula. É um processo desenhado para destravar o que já existe em você, organizando, fortalecendo e colocando em movimento.",
      pillars: [
        ["Diagnóstico honesto", "Antes de qualquer decisão, enxergar onde se está de verdade."],
        ["Resposta consciente", "Sair da reação automática. Construir clareza no momento da pressão."],
        ["Direção sustentável", "Decidir, executar e manter, em perder consistência."],
      ],
    },
    modules: {
      eyebrow: "Os 6 módulos",
      title: "Da consciência à consolidação.",
      sub: "Cada módulo é um capítulo com objetivo, ferramentas e prática. Você pode percorrer em sequência ou começar pelo que mais pesa hoje.",
      items: [
        {
          n: "01",
          title: "Onde Estou de Verdade",
          subtitle: "Diagnóstico inicial",
          short: "Enxergar o momento atual sem ilusão, culpa ou comparação.",
          objective: "Diagnosticar com honestidade nível de estabilidade, forças, fragilidades, padrões e áreas que precisam de atenção, antes de tomar qualquer decisão importante.",
          themes: [
            "Mapa de estabilidade pessoal",
            "Forças e fragilidades reais",
            "Padrões recorrentes",
            "Áreas críticas hoje",
          ],
        },
        {
          n: "02",
          title: "Da Reação à Resposta",
          subtitle: "Emoção, controle e hábito",
          short: "Sair da reação automática e construir respostas mais conscientes.",
          objective: "Parar de ser guiado apenas pelo que sente e começar a responder com mais clareza, maturidade e intenção diante de emoções, pressões, ansiedade e impulsos.",
          themes: [
            "Gatilhos e respostas automáticas",
            "Pausa entre estímulo e ação",
            "Hábitos de regulação",
            "Maturidade emocional aplicada",
          ],
        },
        {
          n: "03",
          title: "Identidade e Direção",
          subtitle: "Para onde eu vou",
          short: "Identificar valores, forças, energia, propósito e caminhos possíveis.",
          objective: "Entender para onde faz sentido caminhar com base em quem você é, no que valoriza e no que deseja construir, reduzindo confusão e dispersão.",
          themes: [
            "Mapa de valores",
            "Energia e vocação",
            "Cenários de futuro",
            "Critérios de direção",
          ],
        },
        {
          n: "04",
          title: "Decisão e Estratégia",
          subtitle: "O que realmente importa agora",
          short: "Avaliar escolhas, separar urgência de importância, decidir com clareza.",
          objective: "Usar ferramentas práticas para avaliar escolhas, entender ganhos e perdas e evitar decisões impulsivas, decidindo com mais consciência, estratégia e responsabilidade.",
          themes: [
            "Matriz de decisão",
            "Custos visíveis e invisíveis",
            "Hierarquia do que importa",
            "Plano de execução",
          ],
        },
        {
          n: "05",
          title: "Quebra de Padrões",
          subtitle: "O que precisa parar de se repetir",
          short: "Reconhecer crenças e ciclos que impedem crescimento e execução.",
          objective: "Identificar o que precisa ser interrompido e treinar novas respostas mais alinhadas com a direção escolhida, quebrando ciclos repetitivos e comportamentos automáticos.",
          themes: [
            "Crenças limitantes",
            "Ciclos repetitivos",
            "Comportamentos automáticos",
            "Novas respostas treináveis",
          ],
        },
        {
          n: "06",
          title: "Consolidação e Compromisso",
          subtitle: "Como sustento a mudança",
          short: "Transformar clareza em prática e sustentar o movimento no tempo.",
          objective: "Organizar os aprendizados da jornada, transformar clareza em prática e criar um compromisso real com os próximos passos, com ação, feedback e continuidade.",
          themes: [
            "Sistema de revisão",
            "Compromissos públicos",
            "Feedback estruturado",
            "Continuidade e ritmo",
          ],
        },
      ],
    },
    notebook: {
      eyebrow: "Materiais da mentoria",
      title: "Dois cadernos. Um caminho.",
      lead: "Cada participante recebe dois materiais editáveis e exclusivos, pensados para sustentar a mudança entre os encontros e transformar reflexão em prática.",
      items: [
        {
          tag: "Material 01",
          name: "Mapa do Autoconhecimento",
          subtitle: "Sua jornada em 6 módulos de mentoria",
          lead: "Um caderno estruturado a partir de seis frameworks aplicados em cada sessão, para você organizar a leitura sobre si, decisões e direção.",
          chips: [
            "IKIGAI · Propósito",
            "Árvore da Vida · Identidade",
            "Círculo de Influência · Foco",
            "Ganhos × Perdas · Decisão",
            "Impacto × Esforço · Priorização",
            "Atual × Ideal · Direção",
          ],
          frameworks: [
            { code: "M01", name: "Matriz de Energia × Drenagem", domain: "Vitalidade · ambientes · pessoas", line: "Mapear o que te energiza e o que te drena, para ajustar onde investir presença." },
            { code: "M02", name: "ICE", domain: "Impacto · Confiança · Facilidade", line: "Framework de priorização para decidir o que executar primeiro com critério, não com pressa." },
            { code: "M03", name: "GUT", domain: "Gravidade · Urgência · Tendência", line: "Hierarquizar problemas por peso real e velocidade com que pioram, antes de agir." },
            { code: "M04", name: "Círculo de Influência", domain: "Foco · controle · energia", line: "Separar o que está sob influência do que apenas gera ruído mental." },
            { code: "M05", name: "Impacto × Esforço", domain: "Priorização · gestão de energia", line: "Onde investir tempo e atenção para gerar resultado real, não apenas movimento." },
            { code: "M06", name: "Ganhos × Perdas", domain: "Decisão consciente · consequências", line: "Avaliar o custo de cada caminho antes de decidir, em vez de reagir ao impulso." },
            { code: "M07", name: "IKIGAI e Árvore da Vida", domain: "Propósito · identidade · raízes", line: "Cruzar razão de ser com narrativa pessoal para definir direção e o que sustenta as escolhas." },
          ],
          mock: {
            label: "Módulo 02 · Árvore da Vida",
            date: "Identidade · Raízes · Direção",
            title: "O que sustenta minhas escolhas hoje.",
            sub: "REFLEXÕES · EXERCÍCIOS · COMPROMISSOS",
            quote: "Não vou agir contra a pessoa que estou me tornando.",
          },
        },
        {
          tag: "Material 02",
          name: "Caderno de 30 Dias",
          subtitle: "Acompanhamento diário e semanal",
          download: { href: "downloads/Caderno-30-Dias.html", filename: "Caderno-30-Dias.html", label: "Baixar grátis", note: "Caderno editável · uso pessoal" },
          lead: "Um ritual leve para registrar o dia, observar padrões, sustentar hábitos essenciais e revisar a semana com honestidade.",
          chips: [
            "Check-in diário",
            "6 hábitos-base",
            "Gestão do estresse",
            "Alimentação consciente",
            "Gratidão e forças",
            "Revisão semanal",
          ],
          frameworks: [
            { code: "01", name: "Check-in diário", domain: "Como cheguei hoje", line: "Estado mental, foco e prioridade do dia em poucos minutos." },
            { code: "02", name: "6 hábitos-base", domain: "Sustentação da rotina", line: "Hidratação, sono, movimento, leitura, gratidão e respiração." },
            { code: "03", name: "Gestão do estresse", domain: "Gatilhos · respostas", line: "Reconhecer o que dispara reação automática e treinar resposta consciente." },
            { code: "04", name: "Alimentação consciente", domain: "Observação, não controle", line: "Perceber padrões, energia e relação com comida sem rigidez." },
            { code: "05", name: "Gratidão e forças", domain: "O que já existe de bom", line: "Treinar o olhar para recursos disponíveis antes do que falta." },
            { code: "06", name: "Revisão semanal", domain: "Vitórias · ajustes · próximo ciclo", line: "Olhar para a semana com honestidade e escolher o próximo passo." },
          ],
          mock: {
            label: "Dia 14 · Semana 02",
            date: "Foco do dia",
            title: "Pausar antes de responder.",
            sub: "CHECK-IN · HÁBITOS · FECHAMENTO",
            quote: "Hoje eu escolho ritmo, não pressa.",
          },
        },
      ],
    },
    services: {
      eyebrow: "Áreas de atuação",
      title: "Onde a Lux & Co. atua.",
      tiers: [
        {
          tag: "Disponível",
          name: "Mentoria Pessoal",
          desc: "Programa individual, em ciclo de 6 módulos. Para quem precisa de clareza, decisão e direção.",
          cta: "Conhecer →",
          target: "modulos",
        },
        {
          tag: "Em breve",
          name: "Consultoria para Empresas",
          desc: "Diagnóstico, estratégia e desenvolvimento de lideranças. Programas sob medida para times.",
          cta: "Saiba mais",
          target: "empresa",
        },
        {
          tag: "Em breve",
          name: "Pacote Integrado",
          desc: "Mentoria pessoal + consultoria empresarial. Para fundadores e líderes que querem alinhar pessoa e negócio.",
          cta: "Saiba mais",
          target: "empresa",
        },
      ],
    },
    contact: {
      eyebrow: "Próximo passo",
      title: "Conversa inicial. Sem custo.",
      lead: "30 minutos para entender o seu momento e descobrir se faz sentido caminharmos juntos.",
      calendly: "https://calendly.com/contact-luxco-consulting/30min",
      calendlyLabel: "Agendar pelo Calendly",
      formFields: {
        name: "Nome",
        email: "E-mail",
        whats: "WhatsApp",
        message: "Qual é o maior desafio que você está enfrentando agora?",
        send: "Envie suas dúvidas",
      },
      ways: [
        ["E-mail", "contact.luxco.consulting@gmail.com", "mailto:contact.luxco.consulting@gmail.com"],
        ["Mobile · WhatsApp", "+61 481 130 970", "https://wa.me/61481130970"],
        ["Localização", "Sydney, Australia", null],
        ["Instagram", "@luxco.consulting", "https://instagram.com/luxco.consulting"],
        ["Facebook", "/luxco.consulting", "https://facebook.com/luxco.consulting"],
      ],
      patronage: {
        eyebrow: "Outras formas de caminhar juntos",
        sponsor: "Quero ser patrocinador / apoiador",
        speaking: "Palestras (convites)",
        sponsorMail: "mailto:contact.luxco.consulting@gmail.com?subject=Quero%20ser%20patrocinador%20%2F%20apoiador",
        speakingMail: "mailto:contact.luxco.consulting@gmail.com?subject=Convite%20para%20palestra",
      },
    },
    detail: {
      objective: "Objetivo",
      themes: "Temas",
      cta: "Quero começar por este módulo",
    },
    footer: {
      tagline: "Think sharp. Move smart.",
      rights: "© 2026 Lux & Co. Consulting. Todos os direitos reservados.",
    },
  },

  en: {
    nav: {
      sobre: "Mentor",
      consultoria: "Practice",
      mentoria: "Mentorship",
      modulos: "Modules",
      caderno: "Notebook · Free",
      contato: "Contact",
      empresa: "For Companies",
    },
    hero: {
      eyebrow: "",
      title: "Stop circling who you could be.\nIt's time to be.",
      sub: "",
      ctaConsultoria: "About the practice",
      ctaMentor: "About the mentor",
      ctaContato: "Get in touch",
    },
    about: {
      eyebrow: "About the mentor",
      title: "Your problem is not lack of EFFORT. It's lack of STRATEGY.",
      identity: {
        name: "Michel Camara Berestinas",
        meta: [
          ["Age", "38 years"],
          ["Born in", "São Paulo, Brazil"],
          ["Based in", "Sydney, Australia"],
          ["Practice", "Worldwide · online"],
        ],
        role: "Project Manager & Account Manager (Google Reviews) · Founder of Lux & Co. Consulting",
      },
      bodyParas: [
        "Hi, my name is Michel C. Berestinas. I'm 38, from São Paulo, and today I'm based in Sydney, Australia, serving people worldwide. With more than 15 years of professional experience, I built my path inside companies like EY, Carrefour, and American Express, in Project Management and Account Management within the Google Reviews area, fast-paced, demanding, results-driven environments.",
        "Along the way I developed a practical view of strategy, business, people, process, service, leadership, and decision-making. I learned firsthand that growth doesn't come from effort alone, it comes from clarity, direction, consistency, and the ability to make good decisions at the right moment.",
        "My experience taught me to look at problems strategically, to understand complex scenarios, to organize priorities, and to turn ideas into viable action. But my story wasn't built only on wins, I've also lived through pressure, uncertainty, restarts, and reconstruction.",
        "Those seasons shaped how I see life, work, and personal development. Over time, I came to understand that most people aren't stuck for lack of potential, they're stuck for lack of clarity, structure, direction, and support to organize what they're living.",
        "Today I turn that experience into a mentorship that is practical, human, and strategic, helping people understand where they are, recognize their patterns, make more conscious decisions, and build a path aligned with their values, strengths, and purpose.",
      ],
      methodEyebrow: "",
      stats: [
        ["15+", "years of experience"],
        ["3", "global corporations"],
        ["1:1", "personalized work"],
        ["FSF", "Created from the FSF method"],
      ],
      brands: ["EY", "Carrefour", "American Express", "Google Reviews"],
      pullquote: "Nobody wakes up one day and finds that life has changed on its own. You can keep waiting for the right moment, or decide the moment is now and build from what you already have.",
      signature: ", Founder, Lux & Co.",
    },
    consultancy: {
      eyebrow: "About the practice",
      welcome: "Welcome.",
      bodyParas: [
        "Many people carry gifts, ideas, and dreams, but without clarity, structure, or direction, that potential stays still.",
        "This mentorship exists to change that.",
        "Here, you'll come to understand who you are, identify what's blocking your progress, and build a practical path for your life, career, and business.",
        "We don't work with generic formulas. We work with what already lives in you, organizing it, strengthening it, and setting it in motion.",
        "Whether to lead with more clarity, build with more discernment, or simply live with more purpose, this is the right place.",
      ],
      quote: "Transformed environments begin when someone decides to think differently.",
      quoteAuthor: "Bill Johnson, leader of Bethel Church",
    },
    mentorship: {
      eyebrow: "The mentorship",
      title: "A structured journey across 6 modules.",
      lead: "Not a formula. A process designed to unlock what already lives in you, organized, strengthened, set in motion.",
      pillars: [
        ["Honest diagnosis", "See where you actually stand, before any major decision."],
        ["Conscious response", "Step out of automatic reaction. Build clarity under pressure."],
        ["Sustainable direction", "Decide, execute, and hold the line, without losing consistency."],
      ],
    },
    modules: {
      eyebrow: "The 6 modules",
      title: "From awareness to consolidation.",
      sub: "Each module is a chapter with a clear objective, tools, and practice. Walk it in sequence, or start where it weighs most today.",
      items: [
        {
          n: "01",
          title: "Where I Actually Stand",
          subtitle: "Initial diagnosis",
          short: "See the present moment without illusion, blame, or comparison.",
          objective: "Honestly diagnose your level of stability, strengths, fragilities, patterns, and areas that need attention, before any important decision.",
          themes: ["Personal stability map", "True strengths and fragilities", "Recurring patterns", "Today's critical areas"],
        },
        {
          n: "02",
          title: "From Reaction to Response",
          subtitle: "Emotion, control, habit",
          short: "Step out of automatic reaction and build conscious responses.",
          objective: "Stop being guided only by what you feel. Begin to respond with more clarity, maturity, and intention under emotion, pressure, anxiety, and impulse.",
          themes: ["Triggers and automatic responses", "The pause between stimulus and action", "Regulation habits", "Applied emotional maturity"],
        },
        {
          n: "03",
          title: "Identity and Direction",
          subtitle: "Where I'm going",
          short: "Identify values, strengths, energy, purpose, and possible paths.",
          objective: "Understand where it makes sense to move based on who you are, what you value, and what you wish to build, reducing confusion and dispersion.",
          themes: ["Map of values", "Energy and vocation", "Future scenarios", "Direction criteria"],
        },
        {
          n: "04",
          title: "Decision and Strategy",
          subtitle: "What truly matters now",
          short: "Evaluate choices, separate urgency from importance, decide clearly.",
          objective: "Use practical tools to evaluate choices, weigh gains and losses, and avoid impulsive decisions, deciding with more consciousness, strategy, and responsibility.",
          themes: ["Decision matrix", "Visible and invisible costs", "Hierarchy of what matters", "Execution plan"],
        },
        {
          n: "05",
          title: "Breaking Patterns",
          subtitle: "What needs to stop repeating",
          short: "Recognize beliefs and cycles that block growth and execution.",
          objective: "Identify what needs to be interrupted and train new responses aligned with the chosen direction, breaking repeating cycles and automatic behaviors.",
          themes: ["Limiting beliefs", "Repeating cycles", "Automatic behaviors", "Trainable new responses"],
        },
        {
          n: "06",
          title: "Consolidation and Commitment",
          subtitle: "How I sustain change",
          short: "Turn clarity into practice and hold the movement over time.",
          objective: "Organize the journey's learnings, turn clarity into practice, and create real commitment to the next steps, through action, feedback, and continuity.",
          themes: ["Review system", "Public commitments", "Structured feedback", "Continuity and rhythm"],
        },
      ],
    },
    notebook: {
      eyebrow: "Mentorship materials",
      title: "Two workbooks. One path.",
      lead: "Every participant receives two editable, private workbooks, designed to sustain change between sessions and turn reflection into practice.",
      items: [
        {
          tag: "Material 01",
          name: "Self-Knowledge Map",
          subtitle: "Your journey across 6 mentorship modules",
          lead: "A structured workbook built around six frameworks applied in every session, so you can organize how you read yourself, your decisions, and your direction.",
          chips: [
            "IKIGAI · Purpose",
            "Tree of Life · Identity",
            "Circle of Influence · Focus",
            "Gains × Losses · Decision",
            "Impact × Effort · Priorities",
            "Current × Ideal · Direction",
          ],
          frameworks: [
            { code: "M01", name: "Energy × Drain Matrix", domain: "Vitality · environments · people", line: "Mapping what energizes you versus what drains you, to redirect where you spend presence." },
            { code: "M02", name: "ICE", domain: "Impact · Confidence · Ease", line: "Prioritization framework to decide what to execute first with criteria, not urgency." },
            { code: "M03", name: "GUT", domain: "Gravity · Urgency · Tendency", line: "Ranking problems by real weight and how fast they get worse, before taking action." },
            { code: "M04", name: "Circle of Influence", domain: "Focus · control · energy", line: "Separating what you can actually influence from what only generates mental noise." },
            { code: "M05", name: "Impact × Effort", domain: "Priorities · energy management", line: "Where to invest time and attention to produce real outcomes, not just motion." },
            { code: "M06", name: "Gains × Losses", domain: "Conscious decision-making", line: "Weighing the cost of each path before deciding, instead of reacting on impulse." },
            { code: "M07", name: "IKIGAI & Tree of Life", domain: "Purpose · identity · roots", line: "Crossing reason for being with personal narrative to define direction and what holds your choices up." },
          ],
          mock: {
            label: "Module 02 · Tree of Life",
            date: "Identity · Roots · Direction",
            title: "What's holding up my choices today.",
            sub: "REFLECTIONS · EXERCISES · COMMITMENTS",
            quote: "I won't act against the person I'm becoming.",
          },
        },
        {
          tag: "Material 02",
          name: "30-Day Companion",
          subtitle: "Daily and weekly tracking",
          download: { href: "downloads/Caderno-30-Dias.html", filename: "30-Day-Companion.html", label: "Download free", note: "Editable workbook · personal use" },
          lead: "A light daily ritual to log the day, notice patterns, sustain a few essential habits, and review each week with honesty.",
          chips: [
            "Daily check-in",
            "6 baseline habits",
            "Stress management",
            "Mindful eating",
            "Gratitude and strengths",
            "Weekly review",
          ],
          frameworks: [
            { code: "01", name: "Daily check-in", domain: "How I'm arriving today", line: "Mental state, focus, and priority of the day in a few minutes." },
            { code: "02", name: "6 baseline habits", domain: "Routine foundation", line: "Hydration, sleep, movement, reading, gratitude, and breath." },
            { code: "03", name: "Stress management", domain: "Triggers · responses", line: "Naming what fires automatic reaction and training conscious response." },
            { code: "04", name: "Mindful eating", domain: "Observation, not control", line: "Noticing patterns, energy, and relationship with food without rigidity." },
            { code: "05", name: "Gratitude and strengths", domain: "What already exists", line: "Training the eye for resources available before what's missing." },
            { code: "06", name: "Weekly review", domain: "Wins · adjustments · next cycle", line: "Looking back honestly and choosing the next step." },
          ],
          mock: {
            label: "Day 14 · Week 02",
            date: "Focus of the day",
            title: "Pause before reacting.",
            sub: "CHECK-IN · HABITS · CLOSING",
            quote: "Today I'm choosing rhythm, not rush.",
          },
        },
      ],
    },
    services: {
      eyebrow: "Areas of practice",
      title: "Where Lux & Co. works.",
      tiers: [
        { tag: "Available", name: "Personal Mentorship", desc: "Individual program in a 6-module cycle. For those who need clarity, decision, and direction.", cta: "Explore →", target: "modulos" },
        { tag: "Coming soon", name: "Corporate Consulting", desc: "Diagnosis, strategy, and leadership development. Tailored programs for teams.", cta: "Learn more", target: "empresa" },
        { tag: "Coming soon", name: "Integrated Package", desc: "Personal mentorship + corporate consulting. For founders and leaders aligning person and business.", cta: "Learn more", target: "empresa" },
      ],
    },
    contact: {
      eyebrow: "Next step",
      title: "Intro call. No charge.",
      lead: "30 minutes to understand your moment and decide if it makes sense to walk together.",
      calendly: "https://calendly.com/contact-luxco-consulting/30min",
      calendlyLabel: "Book on Calendly",
      formFields: {
        name: "Name",
        email: "Email",
        whats: "WhatsApp",
        message: "What is the biggest challenge you are facing right now?",
        send: "Send your questions",
      },
      ways: [
        ["Email", "contact.luxco.consulting@gmail.com", "mailto:contact.luxco.consulting@gmail.com"],
        ["Mobile · WhatsApp", "+61 481 130 970", "https://wa.me/61481130970"],
        ["Location", "Sydney, Australia", null],
        ["Instagram", "@luxco.consulting", "https://instagram.com/luxco.consulting"],
        ["Facebook", "/luxco.consulting", "https://facebook.com/luxco.consulting"],
      ],
      patronage: {
        eyebrow: "Other ways to walk together",
        sponsor: "I want to sponsor / support",
        speaking: "Speaking (invitations)",
        sponsorMail: "mailto:contact.luxco.consulting@gmail.com?subject=I%20want%20to%20sponsor%20%2F%20support",
        speakingMail: "mailto:contact.luxco.consulting@gmail.com?subject=Speaking%20invitation",
      },
    },
    detail: { back: "← Back", objective: "Objective", themes: "Themes", cta: "I want to start with this module" },
    footer: { tagline: "Think sharp. Move smart.", rights: "© 2026 Lux & Co. Consulting. All rights reserved." },
  },
};
